#!/usr/bin/env bash
# Entrypoint wrapper for the ARQ coding worker.
#
# Fixes the Docker daemon DNS race: dockerd reads /etc/resolv.conf once at
# boot to seed its embedded resolver (127.0.0.11) with upstream nameservers.
# On hosts where a DHCP client (dhcpcd, NetworkManager, systemd-resolved)
# writes resolv.conf asynchronously, the daemon can boot during an empty/
# in-flux window and capture zero upstream nameservers, breaking external
# DNS for every container while internal service-name resolution still works.
#
# Approach: the host's live /etc/resolv.conf is mounted read-only at
# /host-resolv.conf (a side path, so the embedded resolver keeps owning
# /etc/resolv.conf and service-name resolution is preserved). We read the
# nameservers from it and append them to the container's /etc/resolv.conf,
# giving the embedded resolver working upstreams without hardcoding any IP.
# This is fully portable: uses whatever the host uses, including networks
# that block public DNS. Then we self-check before launching the worker so
# we never silently burn every job with status=infra_exhausted.
set -euo pipefail

HOST_RESOLV="${HOST_RESOLV:-/host-resolv.conf}"
DNS_PROBE_HOSTS=("ollama.com" "one.one.one.one")
DNS_WAIT_SECONDS="${DNS_WAIT_SECONDS:-30}"
DNS_POLL_INTERVAL="${DNS_POLL_INTERVAL:-2}"

# ---------------------------------------------------------------------------
# 1. Inject the host's nameservers into the container's resolv.conf.
# ---------------------------------------------------------------------------
inject_host_nameservers() {
    if [ ! -r "$HOST_RESOLV" ]; then
        echo "worker-entrypoint: $HOST_RESOLV not readable; skipping upstream injection" >&2
        return 0
    fi
    # Extract nameserver lines from the host resolv.conf (ignore comments/blanks).
    mapfile -t host_ns < <(grep -E '^\s*nameserver\s+' "$HOST_RESOLV" | awk '{print $2}')
    if [ "${#host_ns[@]}" -eq 0 ]; then
        echo "worker-entrypoint: no nameservers found in $HOST_RESOLV; nothing to inject" >&2
        return 0
    fi
    # Append any host nameserver not already present in the container resolv.conf.
    local added=0
    for ns in "${host_ns[@]}"; do
        if ! grep -qE "^\s*nameserver\s+${ns}\s*\$" /etc/resolv.conf 2>/dev/null; then
            echo "nameserver ${ns}" >> /etc/resolv.conf
            added=$((added + 1))
        fi
    done
    echo "worker-entrypoint: injected ${added} host nameserver(s) into /etc/resolv.conf" >&2
}

# /etc/resolv.conf is generated by Docker at container start and is writable.
inject_host_nameservers

# ---------------------------------------------------------------------------
# 2. Self-check: poll external resolution before launching the worker.
# ---------------------------------------------------------------------------
deadline=$(( $(date +%s) + DNS_WAIT_SECONDS ))
ok=0
while [ "$(date +%s)" -lt "$deadline" ]; do
    for host in "${DNS_PROBE_HOSTS[@]}"; do
        if getent hosts "$host" >/dev/null 2>&1; then
            ok=1
            break 2
        fi
    done
    sleep "$DNS_POLL_INTERVAL"
done

if [ "$ok" -ne 1 ]; then
    echo "============================================================" >&2
    echo "DNS_RESOLUTION_FAILED: worker cannot resolve external hosts." >&2
    echo "Probe hosts: ${DNS_PROBE_HOSTS[*]}" >&2
    echo "" >&2
    echo "This is a Docker DNS issue, NOT an LLM/API problem. Every job would" >&2
    echo "fail with status=infra_exhausted and an empty node_history, so the" >&2
    echo "worker is refusing to start." >&2
    echo "" >&2
    echo "Container /etc/resolv.conf contents:" >&2
    cat /etc/resolv.conf >&2
    echo "" >&2
    echo "Host /host-resolv.conf contents:" >&2
    cat "$HOST_RESOLV" >&2 2>/dev/null || echo "(not mounted)" >&2
    echo "" >&2
    echo "Likely causes:" >&2
    echo "  1. The Docker daemon booted before /etc/resolv.conf was populated" >&2
    echo "     (DHCP race) AND the host-resolv.conf mount is missing or empty." >&2
    echo "     Fix: 'sudo systemctl restart docker' then 'docker compose up -d" >&2
    echo "     --force-recreate'." >&2
    echo "  2. The host itself has no working resolver. Provide a" >&2
    echo "     docker-compose.override.yml with an explicit 'dns:' block pointing" >&2
    echo "     at a reachable resolver for each service." >&2
    echo "============================================================" >&2
    exit 1
fi

exec python -m src.worker